# Chart repositories used from within this state file
#
# Use `helm-s3` and `helm-git` and whatever Helm Downloader plugins
# to use repositories other than the official repository or one backend by chartmuseum.
repositories:
  # To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
  - name: istio
    url: "https://istio-release.storage.googleapis.com/charts"
  - name: kyverno
    url: "https://kyverno.github.io/kyverno/"
  - name: falcosecurity
    url: "https://falcosecurity.github.io/charts"
  - name: kiali
    url: "https://kiali.org/helm-charts"

# Default values to set for args along with dedicated keys that can be set by contributors, cli args take precedence over these.
# In other words, unset values results in no flags passed to helm.
# See the helm usage (helm SUBCOMMAND -h) for more info on default values when those flags aren't provided.
helmDefaults:
  # dedicated default key for helm flag --cleanup-on-fail
  cleanupOnFail: true
  # wait for k8s resources via --wait. (default false)
  wait: true
  atomic: true
  # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness) (default 300)
  timeout: 600
  # forces resource update through delete/recreate if needed (default false)
  force: false
  # when using helm 3.2+, automatically create release namespaces if they do not exist (default true)
  createNamespace: true

# The list of environments managed by helmfile.
#
# The default is `environments: {"default": {}}` which implies:
#
# - `{{ .Environment.Name }}` evaluates to "default"
# - `{{ .Values }}` being empty
environments:
  # The "default" environment is available and used when `helmfile` is run without `--environment NAME`.
  default:
    missingFileHandler: Error
    values: []
---
# The desired states of Helm releases.
#
# Helmfile runs various helm commands to converge the current state in the live cluster to the desired state defined here.
releases:
  - name: kyverno
    namespace: kyverno
    chart: kyverno/kyverno

  # - name: falco
  #   namespace: falco
  #   chart: falcosecurity/falco
  #   set:
  #     - name: tty
  #       value: true
  #     - name: falcosidekick.enabled
  #       value: true
  #     - name: falcosidekick.webui.enabled
  #       value: true

  - name: istio-base
    namespace: istio-system
    chart: istio/base
    set:
      - name: defaultRevision
        value: default

  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    hooks:
      - events: ["postsync"]
        command: "kubectl"
        args: ["label", "namespace", "default", "istio-injection=enabled"]
      - events: ["postuninstall"]
        command: "kubectl"
        args: ["label", "namespace", "default", "istio-injection-"]
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          [
            "apply",
            "-f",
            "https://raw.githubusercontent.com/istio/istio/release-1.24/samples/addons/kiali.yaml",
          ]
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          [
            "apply",
            "-f",
            "https://raw.githubusercontent.com/istio/istio/release-1.24/samples/addons/prometheus.yaml",
          ]
      - events: ["preuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          [
            "delete",
            "-f",
            "https://raw.githubusercontent.com/istio/istio/release-1.24/samples/addons/kiali.yaml",
          ]
      - events: ["preuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          [
            "delete",
            "-f",
            "https://raw.githubusercontent.com/istio/istio/release-1.24/samples/addons/prometheus.yaml",
          ]
    needs:
      - istio-system/istio-base

  - name: aggregator
    namespace: default
    chart: ./charts/aggregator
    set:
      - name: aggregator.env.SERVICE_VERBS_URL
        value: http://verbs
      - name: aggregator.env.SERVICE_NOUNS_URL
        value: http://nouns
    needs:
      - kyverno/kyverno
      - istio-system/istio-base
      - istio-system/istiod
